version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  codecov: codecov/codecov@1.1.1

jobs:
  build:
    docker:
      - image: cimg/node:12.18.4
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-firefox
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Run test
          command: npm run test -- --coverage --maxWorkers=2
      - codecov/upload:
          file: reports/coverage/clover.xml
      - store_test_results:
          path: reports
